### ISSUE TITLE
Unable to Instantiate after Instant Run

### ISSUE THREAD

**Issue by rayliverified** [hulab/debugkit#3]
This library is so helpful for debugging code! Thanks for making something great and sharing it with us developers :)

I have been running into a problem that I hope you can shed some light on. Currently, I have DebugKit running in a fragment. When I run new code via Android Studio's Instant Run, the debugger stops working and the window cannot be instantiated. 

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1445)
    at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1463)
    at android.app.BackStackRecord.commitInternal(BackStackRecord.java:708)
    at android.app.BackStackRecord.commit(BackStackRecord.java:672)
    at com.hulab.debugkit.DevTool$Builder.build(DevTool.java:97)
    at stream.secretintro.IntroImportFragment$6.onClick(IntroImportFragment.java:230)
    at android.view.View.performClick(View.java:5685)
    at android.view.View$PerformClick.run(View.java:22481)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:6274)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The DebugKit code is placed in the fragment's onCreateView. 
Here is the code for the onSaveInstanceState: 
```
    @Override
    public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setRetainInstance(true);
        mContext = getContext();
    }
```

This problem makes it very difficult to use DebugKit effectively. Instant Run is much faster than a new build!

**Comment by Nebneb** [comment]
Hi @searchy2,

Thank you very much for your feedback and for reporting this issue.

I can't manage to reproduce this crash, could you show me exactly how you build the debug tool in your fragment's and activity's lifecycle? 

Just looking at the stack trace, I think this is due to the fact that the tool is linked to the activity that initially created it.

**Comment by rayliverified** [comment]
Sorry for not replying sooner. I'll create a demo app to show this issue.

**Comment by rayliverified** [comment]
Closing this issue for now.
